### ISSUE TITLE
Goodhue and Goodsell Printers

### ISSUE THREAD

**Issue by pulpyoj28** [CarletonDevX/web-print#5]
When printing through print.ads, there is only one Goodhue printer available (GHUE-156), in JFP there appear to be 3 more, including a color one!

These 3 more may be the good ol' printers at Goodsell (mistakenly pegged at Goodhue because their ID begins with "GOOD").

There don't appear to be any Goodsell printers available in JFP.

- Charlie

**Comment by dpikt** [comment]
You nailed it, wish I saw this sooner.
