### ISSUE TITLE
Uploading Multiple Documents?

### ISSUE THREAD

**Issue by lbiester** [CarletonDevX/web-print#8]
Are there any plans to support uploading multiple documents at once? If not (and if it's something you guys want), I can try implementing it!

**Comment by Kenadia** [comment]
I say go for it!

**Comment by AdamCanady** [comment]
Would love to have this!

**Comment by alabid** [comment]
++

**Comment by AdamCanady** [comment]
Has anyone taken care of this?

**Comment by AdamCanady** [comment]
[This line](https://github.com/CarletonDevX/web-print/blob/master/chrome/main.html#L36) should have [multiple](http://davidwalsh.name/multiple-file-upload) at the end.

And then something [here](https://github.com/CarletonDevX/web-print/blob/master/chrome/scripts/app/main.js#L505) modifying it with something like [this](http://stackoverflow.com/questions/12989442/uploading-multiple-files-using-formdata/13307822#13307822). Could just be a simple loop to start with, displaying messages like "Printing Document 1 of n" or something.
